// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// Store_search stores data from payload to storage for the search action
func Store_search(
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	fmt.Printf("Stored data for action search successfully\n")
	return nil
}

// LoadFor_search loads stored data for the search action
func LoadFor_search(
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	result := validationutils.ExternalData{}

	fmt.Printf("Loaded external data for action search: %+v\n", result)
	return result, nil
}
