// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package jsonvalidations

import (
	"validationpkg/validationutils"
)

func Status_Tests(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {
	totalResults, err := StatusValidations(input)
	if err != nil {
		return nil, err
	}

	if !input.Config.Debug {
		for i := range totalResults {
			totalResults[i].DebugInfo = nil
		}
	}

	if input.Config.HideParentErrors {
		// Delete results with valid false and no description
		filtered := make([]validationutils.ValidationOutput, 0)
		for _, r := range totalResults {
			if !r.Valid && r.Description == "" {
				continue
			}
			filtered = append(filtered, r)
		}
		totalResults = filtered
	}

	if input.Config.OnlyInvalid {
		res := make([]validationutils.ValidationOutput, 0)
		for _, r := range totalResults {
			if !r.Valid {
				res = append(res, r)
			}
		}

		if len(res) == 0 {
			// Find the overall test result
			var targetSuccess *validationutils.ValidationOutput
			for i := range totalResults {
				if totalResults[i].TestName == "StatusValidations" {
					targetSuccess = &totalResults[i]
					break
				}
			}

			if targetSuccess == nil {
				panic("Critical: Overall test result not found")
			}

			return []validationutils.ValidationOutput{*targetSuccess}, nil
		}

		return res, nil
	}

	return totalResults, nil
}

var StatusValidations = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

	if input.Config.SkipTestsDict != nil {
		if _, skip := input.Config.SkipTestsDict["StatusValidations"]; skip {
			return []validationutils.ValidationOutput{}, nil
		}
	}

	scope := validationutils.GetJsonPath(input.Payload, "$", true)

	subResults := make([]validationutils.ValidationOutput, 0)
	valid := true
	configureDebugInfo := ""
	for _, testObjMap := range scope {
		validationutils.UnusedFunction(testObjMap)

		var STATUS_CONTEXT = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

			if input.Config.SkipTestsDict != nil {
				if _, skip := input.Config.SkipTestsDict["STATUS_CONTEXT"]; skip {
					return []validationutils.ValidationOutput{}, nil
				}
			}

			scope := validationutils.GetJsonPath(input.Payload, "$", true)

			subResults := make([]validationutils.ValidationOutput, 0)
			valid := true
			configureDebugInfo := ""
			for _, testObjMap := range scope {
				validationutils.UnusedFunction(testObjMap)

				var CONTEXT_REQUIRED = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

					if input.Config.SkipTestsDict != nil {
						if _, skip := input.Config.SkipTestsDict["CONTEXT_REQUIRED"]; skip {
							return []validationutils.ValidationOutput{}, nil
						}
					}

					scope := validationutils.GetJsonPath(input.Payload, "$", true)

					subResults := make([]validationutils.ValidationOutput, 0)
					valid := true
					configureDebugInfo := ""
					for _, testObjMap := range scope {
						validationutils.UnusedFunction(testObjMap)

						var REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.location.country.code", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE","attr":"$.context.location.country.code","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE**

- $.context.location.country.code must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_LOCATION_CITY_CODE = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_LOCATION_CITY_CODE"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.location.city.code", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_LOCATION_CITY_CODE","attr":"$.context.location.city.code","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_LOCATION_CITY_CODE",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_LOCATION_CITY_CODE**

- $.context.location.city.code must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_LOCATION_CITY_CODE",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_DOMAIN = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_DOMAIN"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.domain", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_DOMAIN","attr":"$.context.domain","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_DOMAIN",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_DOMAIN**

- $.context.domain must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_DOMAIN",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_TIMESTAMP = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_TIMESTAMP"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.timestamp", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_TIMESTAMP","attr":"$.context.timestamp","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_TIMESTAMP",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_TIMESTAMP**

- $.context.timestamp must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_TIMESTAMP",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_BAP_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_BAP_ID"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bap_id", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_BAP_ID","attr":"$.context.bap_id","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_BAP_ID",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_BAP_ID**

- $.context.bap_id must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_BAP_ID",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_BAP_URI = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_BAP_URI"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bap_uri", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_BAP_URI","attr":"$.context.bap_uri","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_BAP_URI",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_BAP_URI**

- $.context.bap_uri must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_BAP_URI",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_BPP_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_BPP_ID"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bpp_id", true)
								validationutils.UnusedFunction(attr)
								var_search := validationutils.StringSliceToInterface([]string{`search`})
								validationutils.UnusedFunction(var_search)
								action := validationutils.StringSliceToInterface([]string{`status`})
								validationutils.UnusedFunction(action)

								skipCheck := validationutils.AllIn(action, var_search)
								if skipCheck {
									continue
								}

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_BPP_ID","attr":"$.context.bpp_id","var_search":["search"],"_CONTINUE_":"(action all in var_search)","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_BPP_ID",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_BPP_ID**

- $.context.bpp_id must be present in the payload

> **Skip if:**
>
>     - all elements of ["status"] are in ["search"]`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_BPP_ID",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_BPP_URI = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_BPP_URI"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bpp_uri", true)
								validationutils.UnusedFunction(attr)
								var_search := validationutils.StringSliceToInterface([]string{`search`})
								validationutils.UnusedFunction(var_search)
								action := validationutils.StringSliceToInterface([]string{`status`})
								validationutils.UnusedFunction(action)

								skipCheck := validationutils.AllIn(action, var_search)
								if skipCheck {
									continue
								}

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_BPP_URI","attr":"$.context.bpp_uri","var_search":["search"],"_CONTINUE_":"(action all in var_search)","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_BPP_URI",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_BPP_URI**

- $.context.bpp_uri must be present in the payload

> **Skip if:**
>
>     - all elements of ["status"] are in ["search"]`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_BPP_URI",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_TRANSACTION_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_TRANSACTION_ID"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.transaction_id", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_TRANSACTION_ID","attr":"$.context.transaction_id","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_TRANSACTION_ID",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_TRANSACTION_ID**

- $.context.transaction_id must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_TRANSACTION_ID",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_MESSAGE_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_MESSAGE_ID"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.message_id", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_MESSAGE_ID","attr":"$.context.message_id","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_MESSAGE_ID",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_MESSAGE_ID**

- $.context.message_id must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_MESSAGE_ID",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_VERSION = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_VERSION"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.version", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_VERSION","attr":"$.context.version","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_VERSION",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_VERSION**

- $.context.version must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_VERSION",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REQUIRED_CONTEXT_TTL = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REQUIRED_CONTEXT_TTL"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.ttl", true)
								validationutils.UnusedFunction(attr)

								validate := validationutils.ArePresent(attr)

								configureDebugInfo = `{"_NAME_":"REQUIRED_CONTEXT_TTL","attr":"$.context.ttl","_RETURN_":"attr are present","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REQUIRED_CONTEXT_TTL",
										Valid:    false,
										Code:     30000,
										Description: `#### **REQUIRED_CONTEXT_TTL**

- $.context.ttl must be present in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_CONTEXT_TTL",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}

						var testFunctions = validationutils.TestFunctionArray{
							REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE,
							REQUIRED_CONTEXT_LOCATION_CITY_CODE,
							REQUIRED_CONTEXT_DOMAIN,
							REQUIRED_CONTEXT_TIMESTAMP,
							REQUIRED_CONTEXT_BAP_ID,
							REQUIRED_CONTEXT_BAP_URI,
							REQUIRED_CONTEXT_BPP_ID,
							REQUIRED_CONTEXT_BPP_URI,
							REQUIRED_CONTEXT_TRANSACTION_ID,
							REQUIRED_CONTEXT_MESSAGE_ID,
							REQUIRED_CONTEXT_VERSION,
							REQUIRED_CONTEXT_TTL,
						}

						allResults := make([]validationutils.ValidationOutput, 0)

						for _, testFunc := range testFunctions {
							results, err := testFunc(input)
							if err != nil {
								return nil, err
							}
							allResults = append(allResults, results...)
						}

						subResults = allResults
						// if all subResults are valid, then valid is true
						valid = true
						for _, res := range subResults {
							if !res.Valid {
								valid = false
								break
							}
						}

						configureDebugInfo = `NESTED_TEST_OBJECT`

					}

					result := validationutils.ValidationOutput{
						TestName: "CONTEXT_REQUIRED",
						Valid:    valid,
						Code:     0,
						DebugInfo: &validationutils.DebugInfo{
							FedConfig: configureDebugInfo,
						},
					}

					if valid {
						result.Code = 200
					} else {
						result.Code = 30000
					}

					results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
					results = append(results, result)
					results = append(results, subResults...)

					return results, nil
				}
				var CONTEXT_ENUM = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

					if input.Config.SkipTestsDict != nil {
						if _, skip := input.Config.SkipTestsDict["CONTEXT_ENUM"]; skip {
							return []validationutils.ValidationOutput{}, nil
						}
					}

					scope := validationutils.GetJsonPath(input.Payload, "$", true)

					subResults := make([]validationutils.ValidationOutput, 0)
					valid := true
					configureDebugInfo := ""
					for _, testObjMap := range scope {
						validationutils.UnusedFunction(testObjMap)

						var VALID_CONTEXT_LOCATION_COUNTRY_CODE = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["VALID_CONTEXT_LOCATION_COUNTRY_CODE"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.location.country.code", true)
								validationutils.UnusedFunction(attr)
								enumList := validationutils.StringSliceToInterface([]string{`IND`})
								validationutils.UnusedFunction(enumList)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.AnyIn(attr, enumList)

								configureDebugInfo = `{"_NAME_":"VALID_CONTEXT_LOCATION_COUNTRY_CODE","attr":"$.context.location.country.code","_CONTINUE_":"!(attr are present)","enumList":["IND"],"_RETURN_":"attr any in enumList","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "VALID_CONTEXT_LOCATION_COUNTRY_CODE",
										Valid:    false,
										Code:     30000,
										Description: `#### **VALID_CONTEXT_LOCATION_COUNTRY_CODE**

- At least one of $.context.location.country.code must be in ["IND"]

> **Skip if:**
>
>     - $.context.location.country.code is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "VALID_CONTEXT_LOCATION_COUNTRY_CODE",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var VALID_CONTEXT_DOMAIN = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["VALID_CONTEXT_DOMAIN"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.domain", true)
								validationutils.UnusedFunction(attr)
								enumList := validationutils.StringSliceToInterface([]string{`ONDC:FIS12`})
								validationutils.UnusedFunction(enumList)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.AllIn(attr, enumList)

								configureDebugInfo = `{"_NAME_":"VALID_CONTEXT_DOMAIN","attr":"$.context.domain","enumList":["ONDC:FIS12"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr all in enumList","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "VALID_CONTEXT_DOMAIN",
										Valid:    false,
										Code:     30000,
										Description: `#### **VALID_CONTEXT_DOMAIN**

- All elements of $.context.domain must be in ["ONDC:FIS12"]

> **Skip if:**
>
>     - $.context.domain is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "VALID_CONTEXT_DOMAIN",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}

						var testFunctions = validationutils.TestFunctionArray{
							VALID_CONTEXT_LOCATION_COUNTRY_CODE,
							VALID_CONTEXT_DOMAIN,
						}

						allResults := make([]validationutils.ValidationOutput, 0)

						for _, testFunc := range testFunctions {
							results, err := testFunc(input)
							if err != nil {
								return nil, err
							}
							allResults = append(allResults, results...)
						}

						subResults = allResults
						// if all subResults are valid, then valid is true
						valid = true
						for _, res := range subResults {
							if !res.Valid {
								valid = false
								break
							}
						}

						configureDebugInfo = `NESTED_TEST_OBJECT`

					}

					result := validationutils.ValidationOutput{
						TestName: "CONTEXT_ENUM",
						Valid:    valid,
						Code:     0,
						DebugInfo: &validationutils.DebugInfo{
							FedConfig: configureDebugInfo,
						},
					}

					if valid {
						result.Code = 200
					} else {
						result.Code = 30000
					}

					results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
					results = append(results, result)
					results = append(results, subResults...)

					return results, nil
				}
				var CONTEXT_REGEX = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

					if input.Config.SkipTestsDict != nil {
						if _, skip := input.Config.SkipTestsDict["CONTEXT_REGEX"]; skip {
							return []validationutils.ValidationOutput{}, nil
						}
					}

					scope := validationutils.GetJsonPath(input.Payload, "$", true)

					subResults := make([]validationutils.ValidationOutput, 0)
					valid := true
					configureDebugInfo := ""
					for _, testObjMap := range scope {
						validationutils.UnusedFunction(testObjMap)

						var REGEX_CONTEXT_LOCATION_CITY_CODE = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REGEX_CONTEXT_LOCATION_CITY_CODE"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.location.city.code", true)
								validationutils.UnusedFunction(attr)
								reg := validationutils.StringSliceToInterface([]string{`^\*$`})
								validationutils.UnusedFunction(reg)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.FollowRegex(attr, reg)

								configureDebugInfo = `{"_NAME_":"REGEX_CONTEXT_LOCATION_CITY_CODE","attr":"$.context.location.city.code","reg":["^\\*$"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr follow regex reg","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REGEX_CONTEXT_LOCATION_CITY_CODE",
										Valid:    false,
										Code:     30000,
										Description: `#### **REGEX_CONTEXT_LOCATION_CITY_CODE**

- All elements of $.context.location.city.code must follow every regex in ["^\*$"]

> **Skip if:**
>
>     - $.context.location.city.code is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REGEX_CONTEXT_LOCATION_CITY_CODE",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REGEX_CONTEXT_TIMESTAMP = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REGEX_CONTEXT_TIMESTAMP"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.timestamp", true)
								validationutils.UnusedFunction(attr)
								reg := validationutils.StringSliceToInterface([]string{`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$`})
								validationutils.UnusedFunction(reg)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.FollowRegex(attr, reg)

								configureDebugInfo = `{"_NAME_":"REGEX_CONTEXT_TIMESTAMP","attr":"$.context.timestamp","reg":["^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(\\\\.\\\\d+)?(Z|[+-]\\\\d{2}:\\\\d{2})$"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr follow regex reg","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REGEX_CONTEXT_TIMESTAMP",
										Valid:    false,
										Code:     30000,
										Description: `#### **REGEX_CONTEXT_TIMESTAMP**

- All elements of $.context.timestamp must follow every regex in ["^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$"]

> **Skip if:**
>
>     - $.context.timestamp is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REGEX_CONTEXT_TIMESTAMP",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REGEX_CONTEXT_BAP_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REGEX_CONTEXT_BAP_ID"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bap_id", true)
								validationutils.UnusedFunction(attr)
								reg := validationutils.StringSliceToInterface([]string{`^(?!.*\b(?:http|https|www)\b)[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+$`})
								validationutils.UnusedFunction(reg)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.FollowRegex(attr, reg)

								configureDebugInfo = `{"_NAME_":"REGEX_CONTEXT_BAP_ID","attr":"$.context.bap_id","reg":["^(?!.*\\b(?:http|https|www)\\b)[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+$"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr follow regex reg","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REGEX_CONTEXT_BAP_ID",
										Valid:    false,
										Code:     30000,
										Description: `#### **REGEX_CONTEXT_BAP_ID**

- All elements of $.context.bap_id must follow every regex in ["^(?!.*\b(?:http|https|www)\b)[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+$"]

> **Skip if:**
>
>     - $.context.bap_id is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REGEX_CONTEXT_BAP_ID",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REGEX_CONTEXT_BAP_URI = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REGEX_CONTEXT_BAP_URI"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.bap_uri", true)
								validationutils.UnusedFunction(attr)
								reg := validationutils.StringSliceToInterface([]string{`^https?://([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*|localhost)(:\d+)?(/.*)?$`})
								validationutils.UnusedFunction(reg)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.FollowRegex(attr, reg)

								configureDebugInfo = `{"_NAME_":"REGEX_CONTEXT_BAP_URI","attr":"$.context.bap_uri","reg":["^https?://([a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*|localhost)(:\\d+)?(/.*)?$"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr follow regex reg","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REGEX_CONTEXT_BAP_URI",
										Valid:    false,
										Code:     30000,
										Description: `#### **REGEX_CONTEXT_BAP_URI**

- All elements of $.context.bap_uri must follow every regex in ["^https?://([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*|localhost)(:\d+)?(/.*)?$"]

> **Skip if:**
>
>     - $.context.bap_uri is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REGEX_CONTEXT_BAP_URI",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}
						var REGEX_CONTEXT_TTL = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

							if input.Config.SkipTestsDict != nil {
								if _, skip := input.Config.SkipTestsDict["REGEX_CONTEXT_TTL"]; skip {
									return []validationutils.ValidationOutput{}, nil
								}
							}

							scope := validationutils.GetJsonPath(input.Payload, "$", true)

							subResults := make([]validationutils.ValidationOutput, 0)
							valid := true
							configureDebugInfo := ""
							for _, testObjMap := range scope {
								validationutils.UnusedFunction(testObjMap)

								attr := validationutils.GetJsonPath(testObjMap, "$.context.ttl", true)
								validationutils.UnusedFunction(attr)
								reg := validationutils.StringSliceToInterface([]string{`^P(?=\d|T\d)(\d+Y)?(\d+M)?(\d+D)?(T(\d+H)?(\d+M)?(\d+S)?)?$`})
								validationutils.UnusedFunction(reg)

								skipCheck := !(validationutils.ArePresent(attr))
								if skipCheck {
									continue
								}

								validate := validationutils.FollowRegex(attr, reg)

								configureDebugInfo = `{"_NAME_":"REGEX_CONTEXT_TTL","attr":"$.context.ttl","reg":["^P(?=\\\\d|T\\\\d)(\\\\d+Y)?(\\\\d+M)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"],"_CONTINUE_":"!(attr are present)","_RETURN_":"attr follow regex reg","action":["status"],"domain":["ONDC:FIS12"],"version":["2.0.2"]}`

								if !validate {
									result := validationutils.ValidationOutput{
										TestName: "REGEX_CONTEXT_TTL",
										Valid:    false,
										Code:     30000,
										Description: `#### **REGEX_CONTEXT_TTL**

- All elements of $.context.ttl must follow every regex in ["^P(?=\\d|T\\d)(\\d+Y)?(\\d+M)?(\\d+D)?(T(\\d+H)?(\\d+M)?(\\d+S)?)?$"]

> **Skip if:**
>
>     - $.context.ttl is not in the payload`,
										DebugInfo: &validationutils.DebugInfo{
											FedConfig: configureDebugInfo,
										},
									}
									return []validationutils.ValidationOutput{result}, nil
								}

							}

							result := validationutils.ValidationOutput{
								TestName: "REGEX_CONTEXT_TTL",
								Valid:    valid,
								Code:     0,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}

							if valid {
								result.Code = 200
							} else {
								result.Code = 30000
							}

							results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
							results = append(results, result)
							results = append(results, subResults...)

							return results, nil
						}

						var testFunctions = validationutils.TestFunctionArray{
							REGEX_CONTEXT_LOCATION_CITY_CODE,
							REGEX_CONTEXT_TIMESTAMP,
							REGEX_CONTEXT_BAP_ID,
							REGEX_CONTEXT_BAP_URI,
							REGEX_CONTEXT_TTL,
						}

						allResults := make([]validationutils.ValidationOutput, 0)

						for _, testFunc := range testFunctions {
							results, err := testFunc(input)
							if err != nil {
								return nil, err
							}
							allResults = append(allResults, results...)
						}

						subResults = allResults
						// if all subResults are valid, then valid is true
						valid = true
						for _, res := range subResults {
							if !res.Valid {
								valid = false
								break
							}
						}

						configureDebugInfo = `NESTED_TEST_OBJECT`

					}

					result := validationutils.ValidationOutput{
						TestName: "CONTEXT_REGEX",
						Valid:    valid,
						Code:     0,
						DebugInfo: &validationutils.DebugInfo{
							FedConfig: configureDebugInfo,
						},
					}

					if valid {
						result.Code = 200
					} else {
						result.Code = 30000
					}

					results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
					results = append(results, result)
					results = append(results, subResults...)

					return results, nil
				}

				var testFunctions = validationutils.TestFunctionArray{
					CONTEXT_REQUIRED,
					CONTEXT_ENUM,
					CONTEXT_REGEX,
				}

				allResults := make([]validationutils.ValidationOutput, 0)

				for _, testFunc := range testFunctions {
					results, err := testFunc(input)
					if err != nil {
						return nil, err
					}
					allResults = append(allResults, results...)
				}

				subResults = allResults
				// if all subResults are valid, then valid is true
				valid = true
				for _, res := range subResults {
					if !res.Valid {
						valid = false
						break
					}
				}

				configureDebugInfo = `NESTED_TEST_OBJECT`

			}

			result := validationutils.ValidationOutput{
				TestName: "STATUS_CONTEXT",
				Valid:    valid,
				Code:     0,
				DebugInfo: &validationutils.DebugInfo{
					FedConfig: configureDebugInfo,
				},
			}

			if valid {
				result.Code = 200
			} else {
				result.Code = 30000
			}

			results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
			results = append(results, result)
			results = append(results, subResults...)

			return results, nil
		}
		var STATUS_ORDER_ID_PERSONAL_LOAN = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

			if input.Config.SkipTestsDict != nil {
				if _, skip := input.Config.SkipTestsDict["STATUS_ORDER_ID_PERSONAL_LOAN"]; skip {
					return []validationutils.ValidationOutput{}, nil
				}
			}

			scope := validationutils.GetJsonPath(input.Payload, "$", true)

			subResults := make([]validationutils.ValidationOutput, 0)
			valid := true
			configureDebugInfo := ""
			for _, testObjMap := range scope {
				validationutils.UnusedFunction(testObjMap)

				orderidpath := validationutils.GetJsonPath(testObjMap, "$.message.order_id", true)
				validationutils.UnusedFunction(orderidpath)

				skipCheck := !(validationutils.ArePresent(orderidpath))
				if skipCheck {
					continue
				}

				var REQUIRED_STATUS_ORDER_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

					if input.Config.SkipTestsDict != nil {
						if _, skip := input.Config.SkipTestsDict["REQUIRED_STATUS_ORDER_ID"]; skip {
							return []validationutils.ValidationOutput{}, nil
						}
					}

					scope := validationutils.GetJsonPath(input.Payload, "$", true)

					subResults := make([]validationutils.ValidationOutput, 0)
					valid := true
					configureDebugInfo := ""
					for _, testObjMap := range scope {
						validationutils.UnusedFunction(testObjMap)

						attr := validationutils.GetJsonPath(testObjMap, "$.message.order_id", true)
						validationutils.UnusedFunction(attr)

						validate := validationutils.ArePresent(attr)

						configureDebugInfo = `{"_NAME_":"REQUIRED_STATUS_ORDER_ID","attr":"$.message.order_id","_RETURN_":"attr are present","orderidpath":"$._EXTERNAL._SELF.message.order_id"}`

						if !validate {
							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_STATUS_ORDER_ID",
								Valid:    false,
								Code:     30000,
								Description: `#### **REQUIRED_STATUS_ORDER_ID**

- $.message.order_id must be present in the payload`,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}
							return []validationutils.ValidationOutput{result}, nil
						}

					}

					result := validationutils.ValidationOutput{
						TestName: "REQUIRED_STATUS_ORDER_ID",
						Valid:    valid,
						Code:     0,
						DebugInfo: &validationutils.DebugInfo{
							FedConfig: configureDebugInfo,
						},
					}

					if valid {
						result.Code = 200
					} else {
						result.Code = 30000
					}

					results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
					results = append(results, result)
					results = append(results, subResults...)

					return results, nil
				}

				var testFunctions = validationutils.TestFunctionArray{
					REQUIRED_STATUS_ORDER_ID,
				}

				allResults := make([]validationutils.ValidationOutput, 0)

				for _, testFunc := range testFunctions {
					results, err := testFunc(input)
					if err != nil {
						return nil, err
					}
					allResults = append(allResults, results...)
				}

				subResults = allResults
				// if all subResults are valid, then valid is true
				valid = true
				for _, res := range subResults {
					if !res.Valid {
						valid = false
						break
					}
				}

				configureDebugInfo = `NESTED_TEST_OBJECT`

			}

			result := validationutils.ValidationOutput{
				TestName: "STATUS_ORDER_ID_PERSONAL_LOAN",
				Valid:    valid,
				Code:     0,
				DebugInfo: &validationutils.DebugInfo{
					FedConfig: configureDebugInfo,
				},
			}

			if valid {
				result.Code = 200
			} else {
				result.Code = 30000
			}

			results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
			results = append(results, result)
			results = append(results, subResults...)

			return results, nil
		}
		var STATUS_REF_ID_GOLD_LOAN = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

			if input.Config.SkipTestsDict != nil {
				if _, skip := input.Config.SkipTestsDict["STATUS_REF_ID_GOLD_LOAN"]; skip {
					return []validationutils.ValidationOutput{}, nil
				}
			}

			scope := validationutils.GetJsonPath(input.Payload, "$", true)

			subResults := make([]validationutils.ValidationOutput, 0)
			valid := true
			configureDebugInfo := ""
			for _, testObjMap := range scope {
				validationutils.UnusedFunction(testObjMap)

				refidpath := validationutils.GetJsonPath(testObjMap, "$.message.ref_id", true)
				validationutils.UnusedFunction(refidpath)

				skipCheck := !(validationutils.ArePresent(refidpath))
				if skipCheck {
					continue
				}

				var REQUIRED_STATUS_REF_ID = func(input validationutils.ValidationInput) ([]validationutils.ValidationOutput, error) {

					if input.Config.SkipTestsDict != nil {
						if _, skip := input.Config.SkipTestsDict["REQUIRED_STATUS_REF_ID"]; skip {
							return []validationutils.ValidationOutput{}, nil
						}
					}

					scope := validationutils.GetJsonPath(input.Payload, "$", true)

					subResults := make([]validationutils.ValidationOutput, 0)
					valid := true
					configureDebugInfo := ""
					for _, testObjMap := range scope {
						validationutils.UnusedFunction(testObjMap)

						attr := validationutils.GetJsonPath(testObjMap, "$.message.ref_id", true)
						validationutils.UnusedFunction(attr)

						validate := validationutils.ArePresent(attr)

						configureDebugInfo = `{"_NAME_":"REQUIRED_STATUS_REF_ID","attr":"$.message.ref_id","_RETURN_":"attr are present","refidpath":"$._EXTERNAL._SELF.message.ref_id"}`

						if !validate {
							result := validationutils.ValidationOutput{
								TestName: "REQUIRED_STATUS_REF_ID",
								Valid:    false,
								Code:     30000,
								Description: `#### **REQUIRED_STATUS_REF_ID**

- $.message.ref_id must be present in the payload`,
								DebugInfo: &validationutils.DebugInfo{
									FedConfig: configureDebugInfo,
								},
							}
							return []validationutils.ValidationOutput{result}, nil
						}

					}

					result := validationutils.ValidationOutput{
						TestName: "REQUIRED_STATUS_REF_ID",
						Valid:    valid,
						Code:     0,
						DebugInfo: &validationutils.DebugInfo{
							FedConfig: configureDebugInfo,
						},
					}

					if valid {
						result.Code = 200
					} else {
						result.Code = 30000
					}

					results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
					results = append(results, result)
					results = append(results, subResults...)

					return results, nil
				}

				var testFunctions = validationutils.TestFunctionArray{
					REQUIRED_STATUS_REF_ID,
				}

				allResults := make([]validationutils.ValidationOutput, 0)

				for _, testFunc := range testFunctions {
					results, err := testFunc(input)
					if err != nil {
						return nil, err
					}
					allResults = append(allResults, results...)
				}

				subResults = allResults
				// if all subResults are valid, then valid is true
				valid = true
				for _, res := range subResults {
					if !res.Valid {
						valid = false
						break
					}
				}

				configureDebugInfo = `NESTED_TEST_OBJECT`

			}

			result := validationutils.ValidationOutput{
				TestName: "STATUS_REF_ID_GOLD_LOAN",
				Valid:    valid,
				Code:     0,
				DebugInfo: &validationutils.DebugInfo{
					FedConfig: configureDebugInfo,
				},
			}

			if valid {
				result.Code = 200
			} else {
				result.Code = 30000
			}

			results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
			results = append(results, result)
			results = append(results, subResults...)

			return results, nil
		}

		var testFunctions = validationutils.TestFunctionArray{
			STATUS_CONTEXT,
			STATUS_ORDER_ID_PERSONAL_LOAN,
			STATUS_REF_ID_GOLD_LOAN,
		}

		allResults := make([]validationutils.ValidationOutput, 0)

		for _, testFunc := range testFunctions {
			results, err := testFunc(input)
			if err != nil {
				return nil, err
			}
			allResults = append(allResults, results...)
		}

		subResults = allResults
		// if all subResults are valid, then valid is true
		valid = true
		for _, res := range subResults {
			if !res.Valid {
				valid = false
				break
			}
		}

		configureDebugInfo = `NESTED_TEST_OBJECT`

	}

	result := validationutils.ValidationOutput{
		TestName: "StatusValidations",
		Valid:    valid,
		Code:     0,
		DebugInfo: &validationutils.DebugInfo{
			FedConfig: configureDebugInfo,
		},
	}

	if valid {
		result.Code = 200
	} else {
		result.Code = 30000
	}

	results := make([]validationutils.ValidationOutput, 0, len(subResults)+1)
	results = append(results, result)
	results = append(results, subResults...)

	return results, nil
}
